---
# Rate Limiting for API (stricter)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-api
  namespace: {{ .Values.global.serviceNamespace }}
config:
  minute: 100
  hour: 1000
  policy: local
  fault_tolerant: true
  hide_client_headers: false
plugin: rate-limiting
---
# Rate Limiting for Redirects (more lenient)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-redirect
  namespace: {{ .Values.global.serviceNamespace }}
config:
  minute: 1000
  hour: 10000
  policy: local
  fault_tolerant: true
plugin: rate-limiting
---
# CORS for API
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-api
  namespace: {{ .Values.global.serviceNamespace }}
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    - Authorization
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600
plugin: cors
---
# Request Transformer for API
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-api
  namespace: {{ .Values.global.serviceNamespace }}
config:
  add:
    headers:
      - "X-Gateway:Kong"
      - "X-Request-ID:$(uuid)"
  remove:
    headers: []
  replace:
    headers: []
plugin: request-transformer
---
# Proxy Cache for Redirects (Redis-backed)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: proxy-cache-redirect
  namespace: {{ .Values.global.serviceNamespace }}
config:
  strategy: redis
  redis:
    host: redis-service.{{ .Values.global.serviceNamespace }}.svc.cluster.local
    port: 6379
    database: 0
    timeout: 2000
  content_type:
    - "text/plain"
    - "application/json"
  cache_ttl: 300
  cache_control: false
  request_method:
    - GET
    - HEAD
  response_code:
    - 200
    - 301
    - 302
  vary_headers: []
  vary_query_params: []
plugin: proxy-cache
---
# Prometheus Metrics for API
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus-api
  namespace: {{ .Values.global.serviceNamespace }}
config:
  per_consumer: false
plugin: prometheus
---
# Prometheus Metrics for Redirects
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus-redirect
  namespace: {{ .Values.global.serviceNamespace }}
config:
  per_consumer: false
plugin: prometheus
---
# Request Size Limiting
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-size-limiting
  namespace: {{ .Values.global.serviceNamespace }}
config:
  allowed_payload_size: 1
  size_unit: megabytes
plugin: request-size-limiting
---
# IP Restriction (Optional - for admin endpoints)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ip-restriction
  namespace: {{ .Values.global.serviceNamespace }}
config:
  allow:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  status: 403
  message: "Access denied"
plugin: ip-restriction
---
# Request Termination (Circuit Breaker - optional)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-termination
  namespace: {{ .Values.global.serviceNamespace }}
config:
  status_code: 503
  message: "Service temporarily unavailable"
plugin: request-termination
disabled: true
