apiVersion: v2
name: url-psql
description: A Helm chart for the URL Shortener PostgreSQL database
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies: []

keywords:
  - database
  - postgresql
