{{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.name }}-secret
  namespace: {{ .Values.redis.namespace }}
  labels:
    app: redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.redis.auth.password | quote }}
{{- end }}
