apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.filebeat.name }}
  namespace: {{ .Values.filebeat.namespace }}
  labels:
    app: {{ .Values.filebeat.name }}
    component: filebeat
spec:
  selector:
    matchLabels:
      app: {{ .Values.filebeat.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.filebeat.name }}
        component: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      
      containers:
      - name: filebeat
        image: {{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}
        imagePullPolicy: {{ .Values.filebeat.image.pullPolicy }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        resources:
          {{- toYaml .Values.filebeat.resources | nindent 10 }}
        
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - DAC_READ_SEARCH
        
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varpods
          mountPath: /var/log/pods
          readOnly: true
      
      volumes:
      - name: config
        configMap:
          name: filebeat-config
          defaultMode: 0640
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: varpods
        hostPath:
          path: /var/log/pods
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate